const express = require('express')
const app = express()
const cors = require('cors')
const path = require('path')
// const moment = require('moment');
require('dotenv').config()
const port = process.env.PORT
require('./db/mongoose')
app.use(express.json())
app.use(cors())
const momRouter = require('./routers/mom')
const articlesRouter = require('./routers/articles')
const adminRouter = require('./routers/admin')
const doctorRouter = require('./routers/doctor')
const postsRouter = require('./routers/posts')
const Appointment = require('./routers/momAppointment')
const availableAppointment = require('./routers/doctorAvailableAppointments')
const surveyRouter = require('./routers/survey')
const Contact = require('./routers/contactUs')
app.use('/uploads',express.static('uploads'));
app.use(momRouter)
app.use(articlesRouter)
app.use(adminRouter)
app.use(doctorRouter)
app.use(postsRouter)
app.use(Appointment)
app.use(availableAppointment)
app.use(surveyRouter)
app.use(Contact)
app.listen(3000,()=>{
    console.log('Server is running')
})